name: Ruby build
on:
  workflow_dispatch:

jobs:
  RUBY:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{ secrets.IR_API_KEY }}

      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          gem list

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
