source "https://rubygems.org"

# Web framework
gem "sinatra"
gem "puma"
gem "rack"
gem "rack-contrib"
gem "rake"

# HTTP clients
gem "faraday"
gem "faraday-retry"
gem "httparty"
gem "rest-client"
gem "typhoeus"

# Database
gem "pg"
gem "sequel"
gem "activerecord"
gem "connection_pool"
gem "redis"

# Background jobs
gem "sidekiq"
gem "rufus-scheduler"

# Serialization / Parsing
gem "oj"
gem "multi_json"
gem "nokogiri"
gem "json-schema"
gem "csv"

# Auth / Security
gem "bcrypt"
gem "jwt"
gem "omniauth"
gem "rack-attack"

# File / Storage
gem "carrierwave"
gem "mini_magick"
gem "aws-sdk-s3"

# Templating
gem "erb"
gem "slim"
gem "haml"

# Testing
gem "rspec"
gem "faker"
gem "factory_bot"
gem "webmock"
gem "vcr"
gem "simplecov"

# Logging / Monitoring
gem "semantic_logger"
gem "sentry-ruby"
gem "newrelic_rpm"
gem "lograge"

# Utilities
gem "dotenv"
gem "dry-validation"
gem "dry-struct"
gem "virtus"
gem "hashie"
gem "activesupport"
gem "tzinfo"
gem "chronic"
gem "money"
gem "phonelib"
gem "countries"
