services:
  python-api:
    build: ./python-api
    ports:
      - "5000:5000"
    restart: unless-stopped

  node-api:
    build: ./node-api
    ports:
      - "3000:3000"
    restart: unless-stopped
